[package]
name = "animation"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["dylib"]

[dependencies]
glam = { workspace = true }
num-traits = { workspace = true }
bytemuck = { workspace = true }
gltf = { workspace = true }
math = { path = "../math" }